Multi select quick match
advplyr/audiobookshelf pull request #1005
Opened 2022-09-23 18:43 UTC by Undergrid

Adds a feature to allow the user to batch Quick Match the selected audiobooks.

A button is added to the Appbar when one or more audiobooks are selected using the multi-select option (left most button on the below image).

![button](https://user-images.githubusercontent.com/1608488/192035499-423e79f7-e97b-4b58-9993-4adc8bb14438.png)

Once clicked, a dialog is shown allowing the user to select the metadata provider and to select whether exiting covers or metadata should be overwritten.

![dialog](https://user-images.githubusercontent.com/1608488/192035708-e34de784-ebc6-4588-a833-114f6437eff2.png)

When "Continue" is selected, a quick match is run against each selected audiobook, updating metadata and covers as required.

2022-09-23 20:33 UTC, advplyr commented
Awesome. I think we should initialize the provider to whatever the default provider is for the library.

There are some getters in `libraries.js` to get a library provider or get the current library.

Also, we can show the user how many items were updated and how many items were unable to find a match.
Currently the `quickMatchLibraryItem` function is returning a warning if it doesn't find a match. https://github.com/advplyr/audiobookshelf/blob/master/server/scanner/Scanner.js#L695

2022-09-23 21:02 UTC, Undergrid commented
How would you like to show the updated and unmatched count?  Would in the toast be okay?

2022-09-23 21:11 UTC, advplyr commented
Yeah that works, the toast message can have line breaks `\n`.

Eventually we will probably have to change this so that the API request doesn't need to wait for the matches to finish and instead gets the result from a socket event. The reason for that is because some people have very slow systems and the API request will timeout before it finishes.

2022-09-23 21:28 UTC, Undergrid commented
If you can point me at an example of doing that, I can probably get it working that way.  Might as well do it properly from the start.

2022-09-23 21:28 UTC, skyzuma commented
is possible to select details if the switch goes to on, like (update only) language, genre, ... (for selected) ?

2022-09-23 21:47 UTC, advplyr commented
> If you can point me at an example of doing that, I can probably get it working that way. Might as well do it properly from the start.

I don't have a good example to point to yet for this. We would need to set some temporary id locally for the quick match request and setup a socket event listener (something like `batch_quickmatch_complete`). Once finished the backend emits that event including the temporary id so know it is this clients request that was completed.
Most of the socket event listeners are set in the `default.vue` layout.
If you want to go for this that would be great but up to you.

2022-09-23 21:49 UTC, advplyr commented
> is possible to select details if the switch goes to on, like (update only) language, genre, ... (for selected) ?
> 
> li > switch > details ul > swicth > language ul > switch > genre

We don't have support for this in the backend and would be a lot of re-working that is out of the scope of this PR

2022-09-24 18:12 UTC, Undergrid commented
So I'm going to look at the websocket part, but in the mean time I've set the provider and added the counts to the toast.  The toast looks a little different depending on the counts:

![match](https://user-images.githubusercontent.com/1608488/192112658-23cb9b1d-872f-41c0-a615-91cd13f5e495.png)
![nomatch](https://user-images.githubusercontent.com/1608488/192112661-be3517e2-938c-43ea-ae2f-7f401a2d74ef.png)
![matchunmatch](https://user-images.githubusercontent.com/1608488/192112665-17342047-f716-436a-bd26-923c06def8ea.png)
![nomatchunmatch](https://user-images.githubusercontent.com/1608488/192112668-cd76afbb-5e29-4583-9d95-1208d64d86c0.png)

2022-09-24 21:22 UTC, Undergrid commented
@advplyr PR has now been updated as request, including with the websocket feedback etc.

2022-09-24 22:14 UTC, advplyr requested changes

2022-09-24 22:14 UTC, advplyr commented on client/components/modals/BatchQuickMatchModel.vue
> +        })
```suggestion
        .then(() => {
          this.$toast.info('Batch quick match of ' + this.selectedBookIds.length + ' books started!')
        }).catch((error) => {
          this.$toast.error('Batch quick match failed')
          console.error('Failed to batch quick match', error)
        }).finally(() => {
          this.processing = false
          this.$store.commit('setProcessingBatch', false)
          this.show = false
        })
```

2022-09-24 22:14 UTC, advplyr commented on server/controllers/LibraryItemController.js
> +    res.sendStatus(200);
```suggestion
    res.sendStatus(200)
```

2022-09-24 22:14 UTC, advplyr commented on server/controllers/LibraryItemController.js
> +    };
```suggestion
    }
```

2022-09-24 22:14 UTC, advplyr commented on client/components/modals/BatchQuickMatchModel.vue
> +          updateDetails: 'Allow overwriting of existing details for the selected books when a match is located.'
```suggestion
        updateCovers: 'Allow overwriting of existing covers for the selected books when a match is located.',
        updateDetails: 'Allow overwriting of existing details for the selected books when a match is located.'
```

2022-09-24 22:14 UTC, advplyr commented on client/components/modals/BatchQuickMatchModel.vue
> +          <p class="text-base px-8 py-2">Quick Match will attempt to add missing covers and metadata for the selected books.  Enable the options below to allow Quick Match to overwrite existing cover
```suggestion
          <p class="text-base px-8 py-2">Quick Match will attempt to add missing covers and metadata for the selected books. Enable the options below to allow Quick Match to overwrite existing covers and/or metadata.</p>
```

2022-09-24 22:14 UTC, advplyr commented on client/components/modals/BatchQuickMatchModel.vue
> +    },
```suggestion
    }
```

2022-09-24 22:46 UTC, advplyr commented
Works beautifully, thanks!

2022-09-24 22:46 UTC, merged